version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "example-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
    depends_on:
      - hdfs-datanode

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: hdfs-datanode
    env_file:
      - hadoop.env
    volumes:
      - hdfs-datanode:/hadoop/dfs/data
    depends_on:
      - hdfs-namenode

  producer:
    build: ./producer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - hdfs-namenode

volumes:
  hdfs-namenode:
  hdfs-datanode:
